### ISSUE TITLE
Get a github check link when pipeline is running

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/bcdk#29]
## Issue
In the older versions of the pipeline CLI, the jenkins job would display as a check in the repository, this is no longer a feature.

<img width="1308" alt="Screen Shot 2019-06-25 at 10 54 45 AM" src="https://user-images.githubusercontent.com/21046727/60550153-f002d880-9cdb-11e9-8f8c-d2a517b7d874.png">

## Why I want this feature
 This was really handy so that there was an easy way to access the jenkins instance at the correct jobs @ <pr num>. The current __work around__ is to go through openshift and access the name space which is cumbersome.

**Comment by cvarjao** [comment]
@patricksimonian , do you have a reference link to a pull request that has that check?
I am using the "disable-github-multibranch-status" to disable the status because we can't use the branch protection "Require status checks to pass before merging" for all checks since there is always have 1 that will be be in progress for as long as the job is running.
However, we may need to re-consider how we use the checks and the branch protection.

**Comment by patricksimonian** [comment]
https://github.com/bcgov/devhub-app-web/pull/111

if you click 'view details' near the end of the conversation

**Comment by cvarjao** [comment]
BCDK generates with that disabled, but you can enable it by removing that trait in the job config.xml. You just need to remove the following line from your own/generated confi.xml:
```
<com.adobe.jenkins.disable__github__multibranch__status.DisableStatusUpdateTrait plugin="disable-github-multibranch-status@1.1"/>
```
I will change to have that enabled by default.
